[parity]
# Custom chain
chain = "/home/parity/.local/share/io.parity.ethereum/trustlines-spec.json"
keys_path = "/home/parity/.local/share/io.parity.ethereum/custom/keys"
# No updates will be auto-installed
auto_update = "none"
# Disables auto downloading of new releases. Not recommended.
no_download = true


[network]
port = 30300
# Network ID of the chain will be overridden to: 4874
id = 4874
